### ISSUE TITLE
Crashed on "NameError: global name 'inhook' is not defined"

### ISSUE THREAD

**Issue by badbeef** [Cisco-Talos/Decept#4] opened 2018-08-01 23:13 UTC
I'm using the -s switch and just tried the latest master. Getting the following traceback shortly after SSH established:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./lil_sshniffer.py", line 352, in client_handler_helper
    ssh_client_handler(sock,address,out_trans,logfile,kill_switch,hijack_flag)
  File "./lil_sshniffer.py", line 506, in ssh_client_handler
    if inhook:
NameError: global name 'inhook' is not defined

It works fine if I roll back lil_sshniffer.py to previous version

**Comment by Thiefyface** [comment] 2018-08-02 00:55
Okay, so Im not really at a place to update code right now, but Im assuming
youre running on a window box? If so (iirc), due to see windows internals,
globals dont play nicely with threading or multiprocessing modules. Hence
the variable is undefined when its a global.
(more info here:
http://rhodesmill.org/brandon/2010/python-multiprocessing-linux-windows/).
But I could be wrong, lol.

Anyhoo, if you dont feel like waiting a day or two for an update, you could
just throw a 'inhook = "" ' and 'outhook = "" ' in that same function, or
throw the offending lines into a try/except. If youre not the most
comfortable with python, ill have an update out in a day or so, cheers.

**Comment by Thiefyface** [comment] 2018-08-02 14:47
Hopefully the issue should be fixed now, turns out that I forgot to define the 'inhook'/'outhook' variables in the global scope, and also that the 'global inhook'/'global outhook' lines don't actually define the them, go figure. If you used the --hookfile switch (due to loading hooks), they would be defined, which is why I even pushed the changes, since it worked when testing. Forgetting to also test without the flag...I'm a tad embarrassed, apologies.

Side note:  lil_sshniffer seems to be completely broken for Windows ¯\_(ツ)_/¯. 

Anyhoo, if the issue is still occurring, please feel free to reopen the issue. 
Cheers.

**Closed as completed by Thiefyface** 2018-08-02 14:47 UTC

**Comment by badbeef** [comment] 2018-08-02 20:44
Thank you! I will try it out.
